version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPO_URL
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $IMAGE_TAG .
      - echo Tagging the image with $IMAGE_TAG...
      - docker tag $IMAGE_TAG:latest $REPO_URL:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker image to the repository...
      - docker push $REPO_URL:$IMAGE_TAG
      - echo Updating ECS service with the new image...
      - aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
artifacts:
  files:
    - '**/*'
    - appspec.yml
  discard-paths: yes
